OK
NoViableAltException(231@[])
	at org.apache.hadoop.hive.ql.parse.HiveParser.type(HiveParser.java:38682)
	at org.apache.hadoop.hive.ql.parse.HiveParser.colType(HiveParser.java:38439)
	at org.apache.hadoop.hive.ql.parse.HiveParser.columnNameType(HiveParser.java:38123)
	at org.apache.hadoop.hive.ql.parse.HiveParser.columnNameTypeList(HiveParser.java:36247)
	at org.apache.hadoop.hive.ql.parse.HiveParser.createTableStatement(HiveParser.java:5214)
	at org.apache.hadoop.hive.ql.parse.HiveParser.ddlStatement(HiveParser.java:2640)
	at org.apache.hadoop.hive.ql.parse.HiveParser.execStatement(HiveParser.java:1650)
	at org.apache.hadoop.hive.ql.parse.HiveParser.statement(HiveParser.java:1109)
	at org.apache.hadoop.hive.ql.parse.ParseDriver.parse(ParseDriver.java:202)
	at org.apache.hadoop.hive.ql.parse.ParseDriver.parse(ParseDriver.java:166)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:399)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:311)
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1150)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1198)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1087)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1077)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:232)
	at org.apache.hadoop.util.RunJar._main(RunJar.java:148)
	at org.apache.hadoop.util.RunJar.access$000(RunJar.java:52)
	at org.apache.hadoop.util.RunJar$1.run(RunJar.java:139)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1690)
	at org.apache.hadoop.security.SecurityUtil.doAsConfigUser(SecurityUtil.java:649)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
FAILED: ParseException line 4:0 cannot recognize input near 'SELECT' 'userid' ',' in column type
FAILED: SemanticException [Error 10001]: Line 3:14 Table not found 'ndm_user_new'
OK
NoViableAltException(231@[])
	at org.apache.hadoop.hive.ql.parse.HiveParser.type(HiveParser.java:38682)
	at org.apache.hadoop.hive.ql.parse.HiveParser.colType(HiveParser.java:38439)
	at org.apache.hadoop.hive.ql.parse.HiveParser.columnNameType(HiveParser.java:38123)
	at org.apache.hadoop.hive.ql.parse.HiveParser.columnNameTypeList(HiveParser.java:36247)
	at org.apache.hadoop.hive.ql.parse.HiveParser.createTableStatement(HiveParser.java:5214)
	at org.apache.hadoop.hive.ql.parse.HiveParser.ddlStatement(HiveParser.java:2640)
	at org.apache.hadoop.hive.ql.parse.HiveParser.execStatement(HiveParser.java:1650)
	at org.apache.hadoop.hive.ql.parse.HiveParser.statement(HiveParser.java:1109)
	at org.apache.hadoop.hive.ql.parse.ParseDriver.parse(ParseDriver.java:202)
	at org.apache.hadoop.hive.ql.parse.ParseDriver.parse(ParseDriver.java:166)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:399)
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:311)
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1150)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1198)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1087)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1077)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:232)
	at org.apache.hadoop.util.RunJar._main(RunJar.java:148)
	at org.apache.hadoop.util.RunJar.access$000(RunJar.java:52)
	at org.apache.hadoop.util.RunJar$1.run(RunJar.java:139)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1690)
	at org.apache.hadoop.security.SecurityUtil.doAsConfigUser(SecurityUtil.java:649)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
FAILED: ParseException line 4:0 cannot recognize input near 'SELECT' 'userid' ',' in column type
FAILED: SemanticException [Error 10001]: Line 3:14 Table not found 'ndm_user_new'
OK
OK
